# Generated by Django 6.0 on 2026-03-08 10:01

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='用户名')),
                ('prompt_content', models.TextField(verbose_name='提示词内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'AI 提示词',
                'verbose_name_plural': 'AI 提示词列表',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(error_messages={'unique': 'A user with that email already exists.'}, max_length=254, unique=True, verbose_name='email address')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='手机号')),
                ('nickname', models.CharField(blank=True, max_length=50, verbose_name='用户昵称')),
                ('avatar_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='头像URL')),
                ('target_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='目标分数(如: 7.5)')),
                ('current_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='当前预估分数')),
                ('exam_date', models.DateField(blank=True, null=True, verbose_name='预计考试时间')),
                ('membership_tier', models.CharField(choices=[('FREE', '免费用户'), ('PRO', '专业会员'), ('PREMIUM', '尊享会员')], default='FREE', max_length=10, verbose_name='会员等级')),
                ('vip_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='会员过期时间')),
                ('daily_ai_quota', models.IntegerField(default=20, verbose_name='每日剩余生成次数/Token')),
                ('wechat_openid', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='微信OpenID')),
                ('github_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Github ID')),
                ('is_email_verified', models.BooleanField(default=False, verbose_name='邮箱是否验证')),
                ('last_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='最后登录IP')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='信息最后更新时间')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息列表',
                'db_table': 'user_profiles',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
