# Generated by Django 6.0 on 2026-03-08 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='at_balance',
            field=models.IntegerField(default=100, verbose_name='AT币余额'),
        ),
    ]
