# Generated by Django 6.0 on 2026-03-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_at_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_file',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='头像文件路径'),
        ),
    ]
