# Generated by Django 6.0 on 2026-03-08 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_avatar_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='用户名')),
                ('title', models.CharField(max_length=255, verbose_name='反馈标题')),
                ('content', models.TextField(blank=True, null=True, verbose_name='反馈内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'Bug 反馈',
                'verbose_name_plural': 'Bug 反馈列表',
                'ordering': ['-created_at'],
            },
        ),
    ]
