# Generated by Django 6.0 on 2026-03-09 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_problematic',
            field=models.BooleanField(default=False, verbose_name='是否为问题用户'),
        ),
        migrations.AlterField(
            model_name='user',
            name='at_balance',
            field=models.IntegerField(default=10000, verbose_name='AT币余额'),
        ),
    ]
