# Generated by Django 6.0 on 2026-03-09 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_is_problematic_alter_user_at_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_problematic',
        ),
    ]
