# Generated by Django 6.0 on 2026-03-09 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_user_is_problematic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bg_color',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='背景颜色/渐变值'),
        ),
        migrations.AddField(
            model_name='user',
            name='bg_image_url',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='背景图片URL'),
        ),
    ]
