# Generated by Django 6.0 on 2026-03-09 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_user_bg_color_user_bg_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bg_blur',
            field=models.FloatField(default=2.0, verbose_name='背景模糊度(px)'),
        ),
    ]
