# Generated by Django 6.0 on 2026-03-09 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_user_bg_blur'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='is_resolved',
            field=models.BooleanField(default=False, verbose_name='是否解决'),
        ),
    ]
