# Generated by Django 6.0 on 2026-03-10 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_user_is_banned'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='jwt_token_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='当前有效的 Token ID'),
        ),
    ]
