# Generated by Django 6.0 on 2026-03-12 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_aiprompt_title_likes_favorites'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, unique=True, verbose_name='单词原文')),
                ('phonetic', models.CharField(blank=True, max_length=100, null=True, verbose_name='音标')),
                ('definitions', models.JSONField(default=list, help_text='包含词性与中文释义的 JSON 数组', verbose_name='释义列表')),
                ('examples', models.JSONField(default=list, help_text='包含中英对照例句的 JSON 数组', verbose_name='例句列表')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='收录时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '全局词库',
                'verbose_name_plural': '全局词库',
                'db_table': 'vocabulary_words',
            },
        ),
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='生词本名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('is_public', models.BooleanField(default=False, verbose_name='是否公开')),
                ('cover_color', models.CharField(default='indigo', max_length=50, verbose_name='封面颜色/主题')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notebooks', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '生词本',
                'verbose_name_plural': '生词本列表',
                'db_table': 'vocabulary_notebooks',
            },
        ),
        migrations.CreateModel(
            name='NotebookWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mastery_level', models.IntegerField(default=0, verbose_name='掌握度 (0-5)')),
                ('wrong_count', models.IntegerField(default=0, verbose_name='错误次数')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='个人笔记')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('last_reviewed', models.DateTimeField(blank=True, null=True, verbose_name='最后复习时间')),
                ('notebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='api.notebook', verbose_name='所属生词本')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_notebooks', to='api.word', verbose_name='对应单词')),
            ],
            options={
                'verbose_name': '词条记录',
                'verbose_name_plural': '词条记录列表',
                'db_table': 'vocabulary_notebook_words',
                'unique_together': {('notebook', 'word')},
            },
        ),
    ]
