# Generated by Django 6.0 on 2026-03-13 17:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_fill_last_login_for_existing_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='VocabFSRS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200, verbose_name='英文单词')),
                ('zh', models.CharField(blank=True, max_length=500, verbose_name='中文释义')),
                ('due', models.DateTimeField(default=django.utils.timezone.now, verbose_name='下次复习时间')),
                ('stability', models.FloatField(default=0.0, verbose_name='稳定性 S')),
                ('difficulty', models.FloatField(default=0.0, verbose_name='难度 D')),
                ('elapsed_days', models.IntegerField(default=0, verbose_name='距上次复习天数')),
                ('scheduled_days', models.IntegerField(default=0, verbose_name='计划间隔天数')),
                ('reps', models.IntegerField(default=0, verbose_name='总复习次数')),
                ('lapses', models.IntegerField(default=0, verbose_name='遗忘次数')),
                ('state', models.SmallIntegerField(default=0, verbose_name='卡片状态')),
                ('last_review', models.DateTimeField(blank=True, null=True, verbose_name='上次复习时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fsrs_cards', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'FSRS 单词卡',
                'verbose_name_plural': 'FSRS 单词卡',
                'db_table': 'vocab_fsrs_cards',
                'indexes': [models.Index(fields=['user', 'due'], name='idx_vocab_fsrs_user_due')],
                'unique_together': {('user', 'word')},
            },
        ),
    ]
