# Generated by Django 6.0 on 2026-03-13 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_vocabfsrs'),
    ]

    operations = [
        migrations.CreateModel(
            name='VocabBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='词书名称')),
                ('description', models.TextField(blank=True, verbose_name='词书简介')),
                ('cover_image', models.URLField(blank=True, max_length=500, null=True, verbose_name='封面图片')),
                ('word_count', models.IntegerField(default=0, verbose_name='单词数量（缓存）')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '词书',
                'verbose_name_plural': '词书列表',
                'db_table': 'vocab_books',
            },
        ),
        migrations.AddField(
            model_name='word',
            name='grammar',
            field=models.CharField(blank=True, max_length=500, verbose_name='语法标注'),
        ),
        migrations.CreateModel(
            name='WordBookMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='在词书中的序号')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='api.vocabbook', verbose_name='词书')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_memberships', to='api.word', verbose_name='单词')),
            ],
            options={
                'verbose_name': '词书收录',
                'verbose_name_plural': '词书收录列表',
                'db_table': 'vocab_word_book_membership',
            },
        ),
        migrations.AddField(
            model_name='word',
            name='books',
            field=models.ManyToManyField(blank=True, related_name='words', through='api.WordBookMembership', to='api.vocabbook', verbose_name='所属词书'),
        ),
        migrations.CreateModel(
            name='NotebookWordTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='标签名')),
                ('notebook_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='api.notebookword', verbose_name='词条')),
            ],
            options={
                'verbose_name': '词条标签',
                'verbose_name_plural': '词条标签列表',
                'db_table': 'vocab_notebook_word_tags',
                'indexes': [models.Index(fields=['notebook_word'], name='idx_nwtag_entry')],
                'unique_together': {('notebook_word', 'name')},
            },
        ),
        migrations.AddIndex(
            model_name='wordbookmembership',
            index=models.Index(fields=['book', 'order'], name='idx_wbm_book_order'),
        ),
        migrations.AlterUniqueTogether(
            name='wordbookmembership',
            unique_together={('word', 'book')},
        ),
    ]
