# Generated by Django 6.0 on 2026-03-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_vocabbook_word_grammar_wordbookmembership_word_books_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebookword',
            name='custom_zh',
            field=models.CharField(blank=True, max_length=500, verbose_name='用户自定义中文释义'),
        ),
    ]
