# Generated by Django 6.0 on 2026-03-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_learning_plan'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='vocabfsrs',
            name='idx_vocab_fsrs_user_due',
        ),
        migrations.AlterUniqueTogether(
            name='vocabfsrs',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='vocabfsrs',
            name='plan_id',
            field=models.IntegerField(default=0, verbose_name='所属计划ID（0=全局）'),
        ),
        migrations.AlterField(
            model_name='learningplan',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='learningplanentry',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='vocabfsrs',
            unique_together={('user', 'word', 'plan_id')},
        ),
        migrations.AddIndex(
            model_name='vocabfsrs',
            index=models.Index(fields=['user', 'plan_id', 'due'], name='idx_vocab_fsrs_user_plan_due'),
        ),
    ]
