# Generated by Django 6.0 on 2026-03-22 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_user_ai_generation_retry_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocabfsrs',
            name='elapsed_days',
            field=models.FloatField(default=0.0, verbose_name='距上次复习天数'),
        ),
    ]
