# Generated by Django 6.0 on 2026-03-22 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_vocabfsrs_elapsed_days_to_float'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningplan',
            name='default_mode',
            field=models.CharField(default='flashcard', max_length=20, verbose_name='默认学习模式'),
        ),
        migrations.AddField(
            model_name='learningplan',
            name='mastery_target',
            field=models.IntegerField(default=2, verbose_name='连续答对目标次数'),
        ),
        migrations.AddField(
            model_name='user',
            name='ai_provider',
            field=models.CharField(default='deepseek', max_length=20, verbose_name='默认AI提供商'),
        ),
        migrations.AddField(
            model_name='user',
            name='language_preference',
            field=models.CharField(default='zh', max_length=10, verbose_name='语言偏好(zh/en)'),
        ),
        migrations.AddField(
            model_name='user',
            name='target_vocab_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='首选目标生词本'),
        ),
    ]
