# Generated by Django 6.0 on 2026-03-29 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_learningplan_default_mode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='商品名称')),
                ('description', models.TextField(blank=True, verbose_name='商品描述')),
                ('price_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格数值')),
                ('price_currency', models.CharField(choices=[('CNY', '人民币'), ('AT_COIN', 'AT币')], default='CNY', max_length=10, verbose_name='货币类型')),
                ('reward_type', models.CharField(default='AT_COIN', max_length=20, verbose_name='发货类型')),
                ('reward_amount', models.IntegerField(default=0, verbose_name='发货数量(如AT币数量)')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否上架')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品列表',
                'db_table': 'store_products',
            },
        ),
    ]
