# Generated by Django 6.0 on 2026-03-31 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vocab_complete_difficulty',
            field=models.CharField(default='hint', max_length=10, verbose_name='补全模式难度(easy/hint/hard)'),
        ),
    ]
