# Generated by Django 6.0 on 2026-03-31 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_user_vocab_complete_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningplan',
            name='complete_difficulty',
            field=models.CharField(default='hint', max_length=10, verbose_name='拼写难度'),
        ),
    ]
