# Generated by Django 6.0 on 2026-04-10 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_learningplan_complete_difficulty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomMemoryDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='未命名记忆卡组', max_length=100, verbose_name='卡组名称')),
                ('source_text', models.TextField(blank=True, default='', verbose_name='原始文本')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_memory_decks', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '自定义记忆卡组',
                'verbose_name_plural': '自定义记忆卡组',
                'db_table': 'custom_memory_decks',
            },
        ),
        migrations.CreateModel(
            name='CustomMemoryCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_text', models.TextField(verbose_name='正面内容')),
                ('back_text', models.TextField(blank=True, default='', verbose_name='背面内容')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='卡片顺序')),
                ('due', models.DateTimeField(default=django.utils.timezone.now, verbose_name='下次复习时间')),
                ('stability', models.FloatField(default=0.0, verbose_name='稳定性 S')),
                ('difficulty', models.FloatField(default=0.0, verbose_name='难度 D')),
                ('elapsed_days', models.FloatField(default=0.0, verbose_name='距上次复习天数')),
                ('scheduled_days', models.IntegerField(default=0, verbose_name='计划间隔天数')),
                ('reps', models.IntegerField(default=0, verbose_name='总复习次数')),
                ('lapses', models.IntegerField(default=0, verbose_name='遗忘次数')),
                ('state', models.SmallIntegerField(default=0, verbose_name='卡片状态')),
                ('last_review', models.DateTimeField(blank=True, null=True, verbose_name='上次复习时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='api.custommemorydeck', verbose_name='所属卡组')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_memory_cards', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '自定义记忆卡',
                'verbose_name_plural': '自定义记忆卡',
                'db_table': 'custom_memory_cards',
                'unique_together': {('deck', 'order')},
            },
        ),
        migrations.AddIndex(
            model_name='custommemorycard',
            index=models.Index(fields=['user', 'deck', 'due'], name='idx_custom_card_user_deck_due'),
        ),
    ]
