# Generated by Django 6.0 on 2026-04-10 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_custom_memory_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='custommemorydeck',
            name='daily_count',
            field=models.IntegerField(default=20, verbose_name='每日学习卡片数'),
        ),
    ]
