# Generated by Django 6.0 on 2026-04-11 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_custommemorydeck_daily_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreativeWorkshopPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='网页标题')),
                ('method_prompt', models.TextField(verbose_name='学习方法描述')),
                ('generated_html', models.TextField(verbose_name='AI 生成网页源码')),
                ('is_favorited', models.BooleanField(default=False, verbose_name='是否收藏')),
                ('ai_provider', models.CharField(default='deepseek', max_length=30, verbose_name='生成模型提供商')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creative_workshop_pages', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '创意工坊网页',
                'verbose_name_plural': '创意工坊网页',
                'db_table': 'creative_workshop_pages',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', 'is_favorited', 'updated_at'], name='idx_cw_user_fav_updated')],
            },
        ),
    ]
