# Generated by Django 6.0 on 2026-04-12 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_creativeworkshoppage'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDailyLearningTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_date', models.DateField(verbose_name='学习日期')),
                ('total_seconds', models.PositiveIntegerField(default=0, verbose_name='学习时长(秒)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_learning_times', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户每日学习时长',
                'verbose_name_plural': '用户每日学习时长',
                'db_table': 'user_daily_learning_time',
                'unique_together': {('user', 'study_date')},
                'indexes': [models.Index(fields=['user', 'study_date'], name='idx_udlt_user_date')],
            },
        ),
    ]
