# Generated by Django 6.0 on 2026-04-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_userdailylearningtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningplan',
            name='copy_repetitions',
            field=models.PositiveSmallIntegerField(default=3, verbose_name='抄写模式每词次数'),
        ),
        migrations.AddField(
            model_name='learningplan',
            name='copy_review_days',
            field=models.PositiveIntegerField(default=2, verbose_name='抄写完成后复习间隔天数'),
        ),
    ]
