# Generated by Django 6.0 on 2026-04-29 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_learningplan_copy_mode_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakingScenarioHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=500, verbose_name='场景主题')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='生成时间')),
            ],
            options={
                'verbose_name': '口语随机场景历史',
                'verbose_name_plural': '口语随机场景历史列表',
                'db_table': 'speaking_scenario_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
