# Generated by Django 6.0 on 2026-05-03 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_speakingscenariohistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakingTopicBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.SmallIntegerField(verbose_name='考试部分 (1/2/3)')),
                ('category', models.CharField(max_length=100, verbose_name='大类标签')),
                ('date', models.CharField(blank=True, max_length=100, verbose_name='日期批次')),
                ('topic_en', models.CharField(blank=True, max_length=300, verbose_name='英文话题名')),
                ('topic_zh', models.CharField(blank=True, max_length=300, verbose_name='中文话题名')),
                ('questions_json', models.JSONField(default=list, verbose_name='问题列表（Part 1/3）')),
                ('cue_card', models.TextField(blank=True, verbose_name='Cue Card 描述（Part 2）')),
                ('bullet_points_json', models.JSONField(default=list, verbose_name='提示要点（Part 2）')),
                ('times_used', models.IntegerField(default=0, verbose_name='已使用次数')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='入库时间')),
            ],
            options={
                'verbose_name': '口语题库',
                'verbose_name_plural': '口语题库列表',
                'db_table': 'speaking_topic_bank',
                'indexes': [models.Index(fields=['part', 'is_active', 'times_used'], name='idx_sp_bank_part_active_used')],
            },
        ),
    ]
