# Generated by Django 6.0 on 2026-05-04 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_speaking_topic_bank'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('is_checked_in', models.BooleanField(default=False, verbose_name='是否签到')),
                ('checkin_bonus', models.PositiveIntegerField(default=0, verbose_name='签到奖励AT')),
                ('checkin_count', models.PositiveIntegerField(default=0, verbose_name='累计签到次数')),
                ('has_activity', models.BooleanField(default=False, verbose_name='是否有学习活动')),
                ('practice_count', models.PositiveSmallIntegerField(default=0, verbose_name='练习次数')),
                ('speaking_count', models.PositiveSmallIntegerField(default=0, verbose_name='口语练习次数')),
                ('listening_count', models.PositiveSmallIntegerField(default=0, verbose_name='听力练习次数')),
                ('reading_count', models.PositiveSmallIntegerField(default=0, verbose_name='阅读练习次数')),
                ('writing_count', models.PositiveSmallIntegerField(default=0, verbose_name='写作练习次数')),
                ('vocab_count', models.PositiveSmallIntegerField(default=0, verbose_name='词汇练习次数')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户每日统计',
                'verbose_name_plural': '用户每日统计列表',
                'db_table': 'user_daily_stats',
                'indexes': [models.Index(fields=['user', 'date'], name='idx_uds_user_date')],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
