# Generated by Django 6.0 on 2026-05-06 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_user_daily_stats'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkdownNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='笔记标题')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='标签列表')),
                ('content', models.TextField(blank=True, default='', verbose_name='Markdown 内容')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markdown_notes', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'Markdown 笔记',
                'verbose_name_plural': 'Markdown 笔记列表',
                'db_table': 'markdown_notes',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', 'updated_at'], name='idx_mn_user_updated')],
            },
        ),
    ]
