# Generated by Django 6.0 on 2026-05-25 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_markdownnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningplan',
            name='article_review_days',
            field=models.PositiveIntegerField(default=7, verbose_name='文章抄写完成后复习间隔天数'),
        ),
        migrations.CreateModel(
            name='ArticleCopyCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='学习日期')),
                ('article_title', models.CharField(blank=True, max_length=200, verbose_name='文章标题')),
                ('article_text', models.TextField(verbose_name='文章全文')),
                ('word_positions', models.JSONField(default=dict, verbose_name='目标词位置映射')),
                ('ai_provider', models.CharField(default='deepseek', max_length=30, verbose_name='生成模型')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_copy_caches', to='api.learningplan', verbose_name='学习计划')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_copy_caches', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '文章抄写缓存',
                'verbose_name_plural': '文章抄写缓存列表',
                'db_table': 'vocab_article_copy_cache',
                'indexes': [models.Index(fields=['user', 'plan', 'date'], name='idx_acc_user_plan_date')],
                'unique_together': {('user', 'plan', 'date')},
            },
        ),
    ]
