# Generated by Django 6.0 on 2026-05-25 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_add_article_copy_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecopycache',
            name='article_translation',
            field=models.TextField(blank=True, default='', verbose_name='文章中文翻译'),
        ),
        migrations.AddField(
            model_name='articlecopycache',
            name='typed_text',
            field=models.TextField(blank=True, default='', verbose_name='用户已输入的内容'),
        ),
    ]
