# Generated by Django 6.0 on 2026-05-26 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_articlecopycache_article_translation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryModeCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='学习日期')),
                ('story_title', models.CharField(blank=True, max_length=200, verbose_name='故事标题')),
                ('story_text', models.TextField(verbose_name='故事全文')),
                ('clicked_words', models.JSONField(default=list, verbose_name='已点击的单词列表')),
                ('target_words', models.JSONField(default=list, verbose_name='目标单词列表')),
                ('ai_provider', models.CharField(default='deepseek', max_length=30, verbose_name='生成模型')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_mode_caches', to='api.learningplan', verbose_name='学习计划')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_mode_caches', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '剧情模式缓存',
                'verbose_name_plural': '剧情模式缓存列表',
                'db_table': 'vocab_story_mode_cache',
                'indexes': [models.Index(fields=['user', 'plan', 'date'], name='idx_smc_user_plan_date')],
                'unique_together': {('user', 'plan', 'date')},
            },
        ),
    ]
