# Generated by Django 6.0 on 2026-06-01 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_storymodecache'),
    ]

    operations = [
        migrations.CreateModel(
            name='WritingServiceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('correction', '作文批改'), ('task1_teacher', '小作文老师'), ('task2_teacher', '大作文老师'), ('opinion_drill', '观点题特训'), ('typing_chat', '打字聊天')], max_length=50, verbose_name='服务类型')),
                ('title', models.CharField(max_length=255, verbose_name='记录标题')),
                ('content', models.JSONField(verbose_name='生成内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '写作服务记录',
                'verbose_name_plural': '写作服务记录',
                'db_table': 'writing_service_records',
                'ordering': ['-created_at'],
            },
        ),
    ]
