# Generated by Django 6.0 on 2026-06-04 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_writingservicerecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('AT_COIN', 'AT币'), ('CNY', '现金(CNY)')], default='AT_COIN', max_length=20, verbose_name='货币类型')),
                ('amount', models.DecimalField(decimal_places=2, help_text='正数表示增加，负数表示扣除', max_digits=12, verbose_name='交易金额')),
                ('balance_after', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='交易后余额')),
                ('description', models.CharField(max_length=255, verbose_name='交易描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '交易记录',
                'verbose_name_plural': '交易记录',
                'db_table': 'finance_transaction_records',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'currency', 'created_at'], name='idx_txn_user_cur_date')],
            },
        ),
    ]
