# Generated by Django 6.0 on 2026-06-06 22:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_transactionrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserShortcut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('url', models.URLField(max_length=500, verbose_name='链接地址')),
                ('open_in_new_tab', models.BooleanField(default=True, verbose_name='新标签页打开')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortcuts', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户快捷访问',
                'verbose_name_plural': '用户快捷访问',
                'db_table': 'user_shortcuts',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserTodoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='待办内容')),
                ('done', models.BooleanField(default=False, verbose_name='是否完成')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户待办事项',
                'verbose_name_plural': '用户待办事项',
                'db_table': 'user_todo_items',
                'ordering': ['created_at'],
            },
        ),
    ]
