# Generated by Django 6.0 on 2026-06-09 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_usershortcut_usertodoitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='target_listening',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='听力目标分数'),
        ),
        migrations.AddField(
            model_name='user',
            name='target_reading',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='阅读目标分数'),
        ),
        migrations.AddField(
            model_name='user',
            name='target_speaking',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='口语目标分数'),
        ),
        migrations.AddField(
            model_name='user',
            name='target_writing',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='写作目标分数'),
        ),
    ]
