# Generated by Django 6.0 on 2026-07-06 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_bannedip_aiquestion_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiquestion',
            name='skill',
            field=models.CharField(choices=[('reading', '阅读'), ('listening', '听力'), ('writing', '写作'), ('speaking', '口语')], max_length=20, verbose_name='技能类型'),
        ),
    ]
