# Generated by Django 6.0 on 2026-07-08 23:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_alter_aiquestion_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdailystats',
            name='checkin_streak',
            field=models.PositiveIntegerField(default=0, verbose_name='连续签到天数'),
        ),
        migrations.AddField(
            model_name='userdailystats',
            name='is_makeup',
            field=models.BooleanField(default=False, verbose_name='是否补签'),
        ),
        migrations.CreateModel(
            name='UserItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('makeup_card', '补签卡')], max_length=32, verbose_name='物品类型')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='数量')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '背包物品',
                'verbose_name_plural': '背包物品',
                'db_table': 'user_items',
                'unique_together': {('user', 'item_type')},
            },
        ),
    ]
