# Generated by Django 6.0 on 2026-07-13 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_aiquestion_favorited_at_learningplan_favorited_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ai_provider',
            field=models.CharField(default='deepseek', max_length=40, verbose_name='默认AI提供商'),
        ),
        migrations.CreateModel(
            name='CustomAIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='模型名称')),
                ('base_url', models.CharField(max_length=500, verbose_name='接口链接')),
                ('api_key_encrypted', models.TextField(verbose_name='加密密钥')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_ai_models', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '自定义AI模型',
                'verbose_name_plural': '自定义AI模型',
                'db_table': 'custom_ai_models',
                'ordering': ['-created_at'],
            },
        ),
    ]
