# Generated by Django 6.0 on 2026-07-17 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_alter_user_ai_provider_customaimodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiquestion',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.aiquestion', verbose_name='所属全套模拟'),
        ),
        migrations.AlterField(
            model_name='aiquestion',
            name='skill',
            field=models.CharField(choices=[('reading', '阅读'), ('listening', '听力'), ('writing', '写作'), ('speaking', '口语'), ('mock', '全套模拟')], max_length=20, verbose_name='技能类型'),
        ),
    ]
