# Generated by Django 6.0 on 2026-07-19 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_aiquestion_parent_mock_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='用户名')),
                ('prep_duration', models.CharField(blank=True, default='', max_length=20, verbose_name='备考时长')),
                ('target_band', models.CharField(blank=True, default='', max_length=20, verbose_name='目标分数')),
                ('q_all_skills', models.PositiveSmallIntegerField(default=0, verbose_name='四项技能练习有用')),
                ('q_reading_relevant', models.PositiveSmallIntegerField(default=0, verbose_name='AI 阅读材料相关')),
                ('q_listening_clear', models.PositiveSmallIntegerField(default=0, verbose_name='听力 TTS 清晰有用')),
                ('q_speaking_anxiety', models.PositiveSmallIntegerField(default=0, verbose_name='口语练习缓解焦虑')),
                ('q_writing_feedback', models.PositiveSmallIntegerField(default=0, verbose_name='写作反馈指出弱点')),
                ('q_vocab_memory', models.PositiveSmallIntegerField(default=0, verbose_name='词汇复习助记忆')),
                ('q_easy_navigate', models.PositiveSmallIntegerField(default=0, verbose_name='易于导航使用')),
                ('q_recommend', models.PositiveSmallIntegerField(default=0, verbose_name='愿意推荐')),
                ('most_useful', models.TextField(blank=True, default='', verbose_name='最有用之处')),
                ('improvements', models.TextField(blank=True, default='', verbose_name='改进建议')),
                ('other_comments', models.TextField(blank=True, default='', verbose_name='其他评论')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_responses', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '问卷调查',
                'verbose_name_plural': '问卷调查列表',
                'ordering': ['-created_at'],
            },
        ),
    ]
